FROM python:3.10-slim-bookworm

RUN apt update && \
    apt-get install -y unixodbc unixodbc-dev && \
    pip install uv

COPY ./dagster/worker/requirements.txt .
RUN uv pip install --system -r requirements.txt 

# Add code location
WORKDIR /opt/dagster/app
COPY ./dagster/worker /opt/dagster/app

EXPOSE 4001

CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4001", "-f", "definitions.py"]